### ISSUE TITLE
Not availability zones for the instance types suggested

### ISSUE THREAD

**Issue by jesusbv** [SUSE-Enceladus/curated-cloud-installer#30]
Curated-cloud-installer suggest 3 cluster sizes (instace types): 
- small: m5a.large
- medium: m5a.xlarge
- large: m5a.2xlarge

which are not available for region `eu-north-1` 

Possible solution: filter `eu-north-1` in the options when choosing region

Other solution can be informing the user to select a different region but that's an extra step and not great UX, IMHO

Thoughts ?

**Comment by rjschwei** [comment]
Fall back to m5

**Comment by jesusbv** [comment]
Thanks for the reply @rjschwei, do you mean `m5.large` ? 
That region does have a `m5.large` and `m5.metal` instance types (among others) 
I will update the cluster size selection then

**Comment by jesusbv** [comment]
Assuming `m5.large` is guarantee in all AZs, or with another approach of picking first three of `m5*` (i.e. `m5d.large` for small, `m5d.xlarge` for medium and `m5d.2xlarge` for large) then 
the info we tell the user in
![image](https://user-images.githubusercontent.com/3913611/168786251-292fd785-d1b3-43c1-bb32-4e536aae12a3.png)
is probably not true anymore. We could calculate the number of nodes and have that dynamic as well.

Easiest/simplest approach is to validate region when choosing in UI and inform user to pick another in the case of AZ not having the instance type available

Thoughts ?
